version: '3.8'

services:
  sistema_postgres:
    image: postgres:15
    container_name: sistema_postgres
    environment:
      POSTGRES_DB: sistemamonit_dt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sistema_api:
    build: .
    container_name: sistema_api
    depends_on:
      - sistema_postgres
    environment:
      ConnectionStrings__DefaultConnection: Host=sistema_postgres;Port=5432;Database=sistemamonit_dt;Username=postgres;Password=postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: