version: '3.9'

services:
  api:
    build: .
    container_name: sistema_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=monitoramento;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: sistema_postgres
    restart: always
    environment:
      POSTGRES_DB: monitoramento
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
